kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/deewhyweb/custom-eap-image.git'
    openshift.io/generated-by: OpenShiftWebConsole
  name: eap-base-image
  labels:
    app: eap-base-image
    app.kubernetes.io/component: eap-base-image
    app.kubernetes.io/instance: eap-base-image
    app.kubernetes.io/name: eap-base-image
spec:
  lookupPolicy:
    local: false
