apiVersion: wildfly.org/v1alpha1
kind: WildFlyServer
metadata:
  name: eap74
spec:
  applicationImage: 'eap-app-image:latest'
  env:
    - name: POSTGRESQL_HOSTNAME
      value: postgresql
    - name: POSTGRESQL_USER
      valueFrom:
        secretKeyRef:
          key: database-user
          name: postgresql
    - name: POSTGRESQL_PASSWORD
      valueFrom:
        secretKeyRef:
          key: database-password
          name: postgresql
    - name: POSTGRESQL_DB
      valueFrom:
        secretKeyRef:
          key: database-name
          name: postgresql
  replicas: 1
  disableHTTPRoute: true