kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: eap-app
spec:
  to:
    kind: Service
    name: eap74-loadbalancer
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None